

services:
  # Database Service for Doctor
  doctor-db:
    image: postgres:17
    container_name: doctor-db
    environment:
      POSTGRES_USER: doctor
      POSTGRES_PASSWORD: doctor-db
      POSTGRES_DB: doctordb
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U doctor -d doctordb"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - doctor_db_data:/var/lib/postgresql/data

  # Database Service for Patient
  patient-db:
    image: postgres:17
    container_name: patient-db
    environment:
      POSTGRES_USER: patient
      POSTGRES_PASSWORD: patient-db
      POSTGRES_DB: patientdb
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U patient -d patientdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - patient_db_data:/var/lib/postgresql/data

  # Redis Service
  redis:
    image: redis:7
    container_name: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Service for Doctor
  doctor-backend:
    build:
      context: ./doctor-backend
      dockerfile: Dockerfile
    container_name: doctor-backend
    restart: always
    environment:
      DATABASE_URL: ${DOCTOR_DATABASE_URL}
      JWT_SECRET: modieyecare
      HOST: 0.0.0.0
      PORT: 8000
    command: sh -c "npx prisma migrate deploy && npm start"
    ports:
      - "8000:8000"
      - "5555:5555"
    volumes:
      - doctor_uploads:/app/uploads
    depends_on:
      doctor-db:
        condition: service_healthy

  # Backend Service for Patient
  patient-backend:
    build:
      context: ./patient-backend
      dockerfile: Dockerfile
    container_name: patient-backend
    restart: always
    environment:
      DATABASE_URL: ${PATIENT_DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      HOST: 0.0.0.0
      PORT: 8001
    command: sh -c "npx prisma migrate deploy && npm start"
    ports:
      - "8001:8001"
      - "5554:5555"
    volumes:
      - patient_uploads:/app/uploads
    depends_on:
      patient-db:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Proxy Server
  proxy-server:
    build:
      context: ./proxyServer
      dockerfile: Dockerfile
    container_name: proxy-server
    restart: always
    env_file:
      - .env
    environment:
      DOCTOR_URL: ${DOCTOR_URL}
      PATIENT_URL: ${PATIENT_URL}
      HOST: 0.0.0.0
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - doctor-backend
      - patient-backend

# -------------------------
# Persistent Volumes
# -------------------------
volumes:
  doctor_db_data:
  patient_db_data:
  doctor_uploads:
  patient_uploads:
